### PR TITLE
[iRonCub-Mk3] Add Jetpack FTs configuration files

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
Adds also the jetpack FTs to the robot launch files.

### CODE REVIEW

**Comment by davidegorbani** [comment]
Nice!

**Review by davidegorbani — APPROVED** [review]

**Comment by HosameldinMohamed** [comment]
Thanks @davidegorbani 

Some notes:

With this PR, the YARP ports `/icub/left_arm/FT/measures:o` will publish the force/torque and the temperature of both `l_arm_ft_sensor` and `l_jetpack_ft_sensor`.
And `/icub/right_arm/FT/measures:o` will publish the force/torque and the temperature of both `r_arm_ft_sensor` and `r_jetpack_ft_sensor`.

Also, the robot can't be launched with this configuration if the jetpack is unmounted.

**Review by gabrielenava — APPROVED** [review]
nice!

>Also, the robot can't be launched with this configuration if the jetpack is unmounted.

it should not be an issue as long as we have our dedicated `xml` file for the `yarprobotinterface`

**Comment by HosameldinMohamed** [comment]
Thanks guys!

**Pull request merged**
