### PR TITLE
[iRonCub-Mk3] Update WBD with `ftSecondaryCalibImpl` devices and thrust estimation

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
Updates the configuration file of `wholeBodyDynamics` with the current status of the robot and attach `ftSecondaryCalibImpl` devices for `l_arm_ft`, `l_jet_ft`, `r_arm_ft` and `r_jet_ft` FTs. Also publishes estimated thrusts.

`WholeBodyDynamics` publishes the following ports:

- `/wholeBodyDynamics/left_arm_thrust/cartesianEndEffectorWrench:o` publishes the thrust of the left arm turbine, aligned with the -Z force.
- `/wholeBodyDynamics/right_arm_thrust/cartesianEndEffectorWrench:o` publishes the thrust of the right arm turbine, aligned with the -Z force.
- `/wholeBodyDynamics/left_jet_thrust/cartesianEndEffectorWrench:o` publishes the thrust of the left jetpack turbine, aligned with the -Z force.
- `/wholeBodyDynamics/right_jet_thrust/cartesianEndEffectorWrench:o` publishes the thrust of the right jetpack turbine, aligned with the -Z force.
- `/wholeBodyDynamics/left_foot_front/cartesianEndEffectorWrench:o` publishes the contact wrench of the left foot, front part.
- `/wholeBodyDynamics/left_foot_rear/cartesianEndEffectorWrench:o` publishes the contact wrench of the left foot, rear part.
- `/wholeBodyDynamics/right_foot_front/cartesianEndEffectorWrench:o` publishes the contact wrench of the right foot, front part.
- `/wholeBodyDynamics/right_foot_rear/cartesianEndEffectorWrench:o` publishes the contact wrench of the right foot, rear part.

### CODE REVIEW

**Review by gabrielenava — APPROVED** [review]
ok at a first sight, we will test it on the robot next week!

**Comment by davidegorbani** [comment]
Nice!

**Review by davidegorbani — APPROVED** [review]

**Comment by HosameldinMohamed** [comment]
I changed the FT names from `l_arm_ft_sensor` to `l_arm_ft` because `wholeBodyDynamics` requires matching names with the FT sensors in the URDF model.

I created another version of `wholeBodyDynamics` file that works for the robot without the jetpack, and also without the arms. It uses a different URDF file under the robot name `iRonCub-Mk3-FT-ARMS`.

Now the robot can be launched with the command

```
YARP_ROBOT_NAME=iRonCub-Mk3-FT-ARMS yarprobotinterface --config iRonCub_wbd_no-jetpack.xml
```

Passing the robot name `iRonCub-Mk3-FT-ARMS` which is available when installing https://github.com/ami-iit/element_ft-nonlinear-modeling

**Comment by HosameldinMohamed** [comment]
Merged, thanks all!

**Pull request merged**
