### PR TITLE
Increase the lowlevel feedback rate to 1khz

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
cc @isorrentino @traversaro 

This PR is here just for reference to @isorrentino for doing the tests on the robot.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
History fixed 😄 Now the PR is rebased on `devel_iCubGenova09`

**Comment by GiulioRomualdi** [comment]
PR rebased!

**Comment by GiulioRomualdi** [comment]
In https://github.com/ami-iit/robots-configuration/pull/10/commits/504e80e1a178701e5c9fbcb98b99251dd7f9b911 I added the [`YarpRobotLoggerDevice`](https://github.com/ami-iit/bipedal-locomotion-framework/tree/master/devices/YarpRobotLoggerDevice) in the `icub_wbd_logger.xml`, in other words starting the robot interface with  `icub_wbd_logger.xml` we will logg all the data without passing through the `nws` (when possible)

Since it is the first time I play with [`nws` `nwc`](https://github.com/robotology/yarp/discussions/2441) I would like to share with you what I did, @traversaro please correct me if I made some mistakes

### ControlBoardRemapper
In the `YarpRobotLoggerDevice` I attached the device as follows 
https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/telemetry/robotlogger.xml#L59

This device is open here:

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/wrappers/motorControl/alljoints-mc_remapper.xml#L4

As far as I know, we will read the data directly from the shared memory. However it is not clear to me the order of the joints. are they associated to this?

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/wrappers/motorControl/alljoints-mc_remapper.xml#L6-L14

accordingly to the [yarp documentation](https://www.yarp.it/latest/classControlBoardRemapper.html), the only parameter required is `axesNames` however here the parameters are different. Am I missing something? 

### FTs

In the `YarpRobotLoggerDevice` I attached the device as follows 
https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/telemetry/robotlogger.xml#L61-L67

This is similar to what is done in wbd

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/estimators/wholebodydynamics.xml#L119-L125

### Cartesian wrenches

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/telemetry/robotlogger.xml#L69-L75

as far I understood it is not possible to pass the yarp network since the device we use here is a [`genericSensorClient`](https://github.com/robotology/whole-body-estimators/tree/dccb968f60152bbeeaaf1665cb6f738635b9ee1a/devices/genericSensorClient)
For this reason I added the following files
image


### head IMU (multi-analog sensor)

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/telemetry/robotlogger.xml#L77

here I copied what is done in wbd 

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/estimators/wholebodydynamics.xml#L111

where `head-inertial` is defined here:

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/hardware/inertials/head-inertial.xml#L6

notice that I didn't have to change 

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/telemetry/robotlogger.xml#L47-L52

since the names are the same of the one defined in the `head-inertial` device 

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/hardware/inertials/head-inertial.xml#L32-L40

**Comment by GiulioRomualdi** [comment]
Running the yarprobotinterface  I got the following error
```
[INFO] Executing attach action, level 15 on device yarp-robot-logger with parameters [("networks" = "(all_joints left_front_ft_client left_rear_ft_client right_front_ft_client right_rear_ft_client right_upper_leg_ft_client left_arm_ft_client right_arm_ft_client left_front_wrench_client left_rear_wrench_client right_front_wrench_client right_rear_wrench_client right_arm_wrench_client left_arm_wrench_client right_upper_leg_wrench_client imu)"), ("all_joints" = "alljoints-mc_remapper"), ("left_front_ft_client" = "left_leg-eb8-j3_5-strain"), ("left_rear_ft_client" = "left_leg-eb7-j0_2-strain"), ("right_front_ft_client" = "right_leg-eb12-j3_5-strain"), ("right_rear_ft_client" = "right_leg-eb11-j0_2-strain"), ("right_upper_leg_ft_client" = "torso-eb5-j0_2-strain"), ("left_arm_ft_client" = "left_arm-eb1-j0_1-strain"), ("right_arm_ft_client" = "right_arm-eb3-j0_1-strain"), ("left_front_wrench_client" = "left_front_wrench_client"), ("left_rear_wrench_client" = "left_rear_wrench_client"), ("right_front_wrench_client" = "right_front_wrench_client"), ("right_rear_wrench_client" = "right_rear_wrench_client"), ("right_arm_wrench_client" = "right_arm_wrench_client"), ("left_arm_wrench_client" = "left_arm_wrench_client"), ("right_upper_leg_wrench_client" = "right_upper_leg_wrench_client"), ("imu" = "head-inertial")]
[ERROR] [2022-03-07 14:11:10.734] [thread: 10012] [blf] [YarpSensorBridge::Impl::compareControlBoardJointsList] Could not find a desired joint from the configuration in the attached control board remapper.
[ERROR] [2022-03-07 14:11:10.734] [thread: 10012] [blf] [YarpSensorBridge::Impl::attachRemappedRemoteControlBoard] Could not attach to remapped control board interface.
[ERROR] [2022-03-07 14:11:10.735] [thread: 10012] [blf] [YarpSensorBridge::setDriversList] Failed to attach to one or more device drivers.
[ERROR] [2022-03-07 14:11:10.735] [thread: 10012] [blf] [YarpRobotLoggerDevice::attachAll] Could not attach drivers list to sensor bridge.
[ERROR] Device yarp-robot-logger cannot execute attach
[ERROR] Cannot run attach action on device yarp-robot-logger
```
This happens when I enable the logging of the joint/motorstate. Notice that blf uses the controlboardremapper to get the joint state and not separate controlboards as in wbd.
In theory I've run the controlboardremapper device by adding this device in the main robotinterface. 

https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/wrappers/motorControl/alljoints-mc_remapper.xml#L6-L14

am I missing something? @traversaro

**Comment by GiulioRomualdi** [comment]
Removing the logging of the joints/motor I got another error
```
[INFO] Executing attach action, level 15 on device yarp-robot-logger with parameters [("networks" = "(all_joints left_front_ft_client left_rear_ft_client right_front_ft_client right_rear_ft_client right_upper_leg_ft_client left_arm_ft_client right_arm_ft_client left_front_wrench_client left_rear_wrench_client right_front_wrench_client right_rear_wrench_client right_arm_wrench_client left_arm_wrench_client right_upper_leg_wrench_client imu)"), ("all_joints" = "alljoints-mc_remapper"), ("left_front_ft_client" = "left_leg-eb8-j3_5-strain"), ("left_rear_ft_client" = "left_leg-eb7-j0_2-strain"), ("right_front_ft_client" = "right_leg-eb12-j3_5-strain"), ("right_rear_ft_client" = "right_leg-eb11-j0_2-strain"), ("right_upper_leg_ft_client" = "torso-eb5-j0_2-strain"), ("left_arm_ft_client" = "left_arm-eb1-j0_1-strain"), ("right_arm_ft_client" = "right_arm-eb3-j0_1-strain"), ("left_front_wrench_client" = "left_front_wrench_client"), ("left_rear_wrench_client" = "left_rear_wrench_client"), ("right_front_wrench_client" = "right_front_wrench_client"), ("right_rear_wrench_client" = "right_rear_wrench_client"), ("right_arm_wrench_client" = "right_arm_wrench_client"), ("left_arm_wrench_client" = "left_arm_wrench_client"), ("right_upper_leg_wrench_client" = "right_upper_leg_wrench_client"), ("imu" = "head-inertial")]
[ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::Impl::attachGenericOrAnalogSensor] left_front_wrench_client Mismatch in the expected number of channels in the sensor stream.
[ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::Impl::attachAllGenericOrAnalogSensors] Could not attach all desired Cartesian Wrench Interface.
[ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::setDriversList] Failed to attach to one or more device drivers.
[ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpRobotLoggerDevice::attachAll] Could not attach drivers list to sensor bridge.
```

cc @prashanthr05

**Comment by traversaro** [comment]
> However it is not clear to me the order of the joints. are they associated to this?
> accordingly to the [yarp documentation](https://www.yarp.it/latest/classControlBoardRemapper.html), the only parameter required is axesNames however here the parameters are different. Am I missing something?

Yes. The `networks` group can be used in place of the `axesNames`, as mentioned in the following sentence in the docs:
> For compatibility with the controlboardwrapper2, the networks keyword can also be used to select the desired joints. For more information on the syntax of the networks, see the [ControlBoardWrapper](https://www.yarp.it/latest/classControlBoardWrapper.html) class.

You can read about the meaning of those numbers in the controlboardwrapper2 docs, i.e. in a nutshell:
> describe how to match subdevice_1 joints with the wrapper joints. First 2 numbers indicate first/last wrapper joint, last 2 numbers are subdevice first/last joint 

I never found these intuitive, that is the reason why I introduced `axesNames` in the first place. :D
If you prefer the axesNames format we can  use it there without problems.

**Comment by traversaro** [comment]
>  In theory I've run the controlboardremapper device by adding this device in the main robotinterface.

Where did you added it? By checking in https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/icub_wbd_logger.xml I did not see the device added anywhere, but I am not 100% sure this is the xml file used.

**Comment by GiulioRomualdi** [comment]
> > In theory I've run the controlboardremapper device by adding this device in the main robotinterface.
> 
> Where did you added it? By checking in https://github.com/ami-iit/robots-configuration/blob/504e80e1a178701e5c9fbcb98b99251dd7f9b911/iCubGenova09/icub_wbd_logger.xml I did not see the device added anywhere, but I am not 100% sure this is the xml file used.


Here: https://github.com/ami-iit/robots-configuration/pull/10/commits/3088fc08b9d9d044bade700241be8eab2f761995 Sorry but I change yesterday 😃

**Comment by prashanthr05** [comment]
> Removing the logging of the joints/motor I got another error
> 
> ```
> [INFO] Executing attach action, level 15 on device yarp-robot-logger with parameters [("networks" = "(all_joints left_front_ft_client left_rear_ft_client right_front_ft_client right_rear_ft_client right_upper_leg_ft_client left_arm_ft_client right_arm_ft_client left_front_wrench_client left_rear_wrench_client right_front_wrench_client right_rear_wrench_client right_arm_wrench_client left_arm_wrench_client right_upper_leg_wrench_client imu)"), ("all_joints" = "alljoints-mc_remapper"), ("left_front_ft_client" = "left_leg-eb8-j3_5-strain"), ("left_rear_ft_client" = "left_leg-eb7-j0_2-strain"), ("right_front_ft_client" = "right_leg-eb12-j3_5-strain"), ("right_rear_ft_client" = "right_leg-eb11-j0_2-strain"), ("right_upper_leg_ft_client" = "torso-eb5-j0_2-strain"), ("left_arm_ft_client" = "left_arm-eb1-j0_1-strain"), ("right_arm_ft_client" = "right_arm-eb3-j0_1-strain"), ("left_front_wrench_client" = "left_front_wrench_client"), ("left_rear_wrench_client" = "left_rear_wrench_client"), ("right_front_wrench_client" = "right_front_wrench_client"), ("right_rear_wrench_client" = "right_rear_wrench_client"), ("right_arm_wrench_client" = "right_arm_wrench_client"), ("left_arm_wrench_client" = "left_arm_wrench_client"), ("right_upper_leg_wrench_client" = "right_upper_leg_wrench_client"), ("imu" = "head-inertial")]
> [ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::Impl::attachGenericOrAnalogSensor] left_front_wrench_client Mismatch in the expected number of channels in the sensor stream.
> [ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::Impl::attachAllGenericOrAnalogSensors] Could not attach all desired Cartesian Wrench Interface.
> [ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpSensorBridge::setDriversList] Failed to attach to one or more device drivers.
> [ERROR] [2022-03-07 14:22:00.800] [thread: 10408] [blf] [YarpRobotLoggerDevice::attachAll] Could not attach drivers list to sensor bridge.
> ```
> 
> cc @prashanthr05


Sorry, just noticed this comment in my email. But, magically (timing of appearance), we fixed this issue f2f ;D

We had to attach all the hardware boards of motorControl associated with only head, arms, torso, and legs. And remap a subset of 26 joints instead of 54 joints.

**Comment by GiulioRomualdi** [comment]
Closing in favor of https://github.com/ami-iit/robots-configuration/pull/20

**Pull request closed without merging**
