### PR TITLE
Increase interface frequency to 500 Hz for iRonCub experiments

### PR DESCRIPTION
**Pull request by gabrielenava**
cc @GiulioRomualdi @HosameldinMohamed @isorrentino @antonellopaolino @DanielePucci @traversaro

### CODE REVIEW

**Comment by gabrielenava** [comment]
I have noted some things:

- there is a huge number of  deprecated - unused files. See e.g. 
 https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova04_higherFreq/iRonCub-Mk1/estimators
https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova04_higherFreq/iRonCub-Mk1/wrappers/inertials

- the waist-IMU interface is not very clear. we don't use the [associated wrapper](https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/wrappers/inertials/waist-inertials_wrapper.xml) because it is not called in [iRonCub_wbd_noFeetFTs.xml](https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/iRonCub_wbd_noFeetFTs.xml). Instead we open a port directly from  [this file](https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/hardware/inertials/waist-inertial.xml). I've added in that file the [time step](https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/hardware/inertials/waist-inertial.xml#L7) as per YARP documentation https://www.yarp.it//git-master/classServerInertial.html#details

- there was a reference to a deprecated file in [iRonCub_wbd_noFeetFTs.xml](https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/iRonCub_wbd_noFeetFTs.xml), see  https://github.com/ami-iit/robots-configuration/pull/16/files#diff-0d2b3ba6a3a68c4f07304938f668db371cc19b50cdae7cd15328fe387c1193dcL47

**Comment by gabrielenava** [comment]
decrease this parameter https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iCubGenova09/hardware/electronics/left_arm-eb1-j0_1-eln.xml#L32

to set the frequency at which the debugger verifies if the packages are not processed in time by the icub-head pc

**Comment by HosameldinMohamed** [comment]
I think we can proceed with this PR now @gabrielenava!

**Review by HosameldinMohamed — APPROVED** [review]
The branch contains files of another robot `iCubGenova04-no_arms` and some files regarding the skin.

But I think we can merge!

**Comment by gabrielenava** [comment]
thanks Hosam! merging!

**Comment by DanielePucci** [comment]
Super cool

**Pull request merged**
