### PR TITLE
Add telemetry-logger application

### PR DESCRIPTION
**Pull request by paolo-viceconte**
Following https://github.com/ami-iit/component_ANA-Avatar-XPRIZE/issues/449, this PR is to add an application to use the telemetry-logger from yarpmanager.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Sorry @paolo-viceconte I lost track of this. Can you please rebase on top of ``devel_iCubGenova09``?

**Comment by paolo-viceconte** [comment]
> Sorry @paolo-viceconte I lost track of this. Can you please rebase on top of `devel_iCubGenova09`?

Yes. In case of conflicts, I'll keep track of them here.

**Comment by paolo-viceconte** [comment]
There are indeed several conflicts.

1. Conflicts on `iCubGenova09/calibrators/left_arm-calib.xml`:

```
diff --cc iCubGenova09/calibrators/left_arm-calib.xml
index 60b869161,af166c10d..000000000
--- a/iCubGenova09/calibrators/left_arm-calib.xml
+++ b/iCubGenova09/calibrators/left_arm-calib.xml
@@@ -16,17 -16,17 +16,26 @@@
  </group>                                                                        
                                                                                  
  <group name="CALIBRATION">                                                      
 -<param name="calibrationType">        12          12          12         12          5       12      12      7       7       6       6       6       6       6       6       6       </param> <!-- 
 +<param name="calibrationType">        10          10          10         10          5       12      12      7       7       6       6       6       6       6       6       6       </param> <!-- 
  <param name="calibration1">           -54795      22399       44679      53215    -1500     -8335   10671    0       0       0       0       0       0       0       0       0       </param> -->
++<<<<<<< HEAD
 +<param name="calibration1">           4000        -3000       -3000      4000    -1500     63919   12031     0       0       0       0       0       0       0       0       0       </param>
 +<param name="calibration2">          0           0           0          0        16384      0       0        0       0       9102    9102    9102    9102    9102    9102    10000    </param>
 +<param name="calibration3">           0           0           0          0           0       0       0       0       0      -1        1       -1      1      -1       1       1      </param>
 +<param name="calibration4">           0           0           0          0           0       0       0       1948    325     250     478     243     483     255     480     725     </param>
 +<param name="calibration5">           0           0           0          0           0       0       0       2073    2730    9       99       15      8       30      45      125     </param>
 +<param name="calibrationZero">        25       -8.4        -51.3       -5           0       0       0       0       0       0       0       0       0       0       0       0       </param>
++=======
+ <param name="calibration1">           -54795      19668       44679      53215    -1500     -8335   10671    0       0       0       0       0       0       0       0       0       </param>
+ <param name="calibration2">         0           0           0          0        16384      0       0       0       0       9102    9102    9102    9102    9102    9102    10000    </param>
+ <param name="calibration3">           0           0           0          0           0       0       0       0       0       -1      1       -1      1      -1       1       1      </param>
+ <param name="calibration4">           0           0           0          0           0       0       0       2045    448     240     484     243     483     255     480     725     </param>
+ <param name="calibration5">           0           0           0          0           0       0       0       2140    2712    0       9       15      8      20      45      125     </param>
+ <param name="calibrationZero">        0           0           0          0           0       0       0       0       0       0       0       0       0       0       0       0       </param>
++>>>>>>> Updated head and left arm calib after maintenance.
  <param name="calibrationDelta">       0           0           0          0           0       0       0       0       0       0       0       0       0       0       0       0       </param>
                                                                                                                               
 -<param name="startupPosition">        -35        30           0         45           0       0       0       25      45      0       0       0       0       0       0       0       </param>
 +<param name="startupPosition">        24        50            0        10           -75       0       0       25      45      0       0       0       0       0       0       0       </param>
  <param name="startupVelocity">        10.0       10.0         10.0      10.0         30      30      30      60      100     100     100     100     100     100     100     100     </param>
  <param name="startupMaxPwm">          8000       8000         8000      8000         2000    0       0       0       0       0       0       0       0       0       0       0       </param>
  <param name="startupPosThreshold">    2          2            2          2           90      90      90      90      90      90      90      90      90      90      90      90      </param>
```

2. Conflicts on `iCubGenova09/hardware/mechanicals/left_arm-eb2-j2_3-mec.xml`:

```
diff --cc iCubGenova09/hardware/mechanicals/left_arm-eb2-j2_3-mec.xml
index ec897d58e,708056c3c..000000000
--- a/iCubGenova09/hardware/mechanicals/left_arm-eb2-j2_3-mec.xml
+++ b/iCubGenova09/hardware/mechanicals/left_arm-eb2-j2_3-mec.xml
@@@ -21,7 -21,7 +21,11 @@@
      <group name="LIMITS">
          <!--                                    0                   1                   -->
          <param name="hardwareJntPosMax">        82                  105                  </param>  
++<<<<<<< HEAD
 +        <param name="hardwareJntPosMin">       -51.3                 -5                   </param>
++=======
+         <param name="hardwareJntPosMin">       -52                 -5                   </param>
++>>>>>>> New hardware limits on the elbow
          <param name="rotorPosMin">              0                   0                   </param> 
          <param name="rotorPosMax">              0                   0                   </param>
      </group>
```

3. Conflicts on `iCubGenova09/hardware/mechanicals/right_arm-eb4-j2_3-mec.xml`:

```
diff --cc iCubGenova09/hardware/mechanicals/right_arm-eb4-j2_3-mec.xml
index 29826bcec,ac9938a81..000000000
--- a/iCubGenova09/hardware/mechanicals/right_arm-eb4-j2_3-mec.xml
+++ b/iCubGenova09/hardware/mechanicals/right_arm-eb4-j2_3-mec.xml
@@@ -21,7 -21,7 +21,11 @@@
      <group name="LIMITS">
          <!--                                    0                   1                   -->
          <param name="hardwareJntPosMax">        82                  105                  </param>  
++<<<<<<< HEAD
 +        <param name="hardwareJntPosMin">       -51.3                 -5                  </param>
++=======
+         <param name="hardwareJntPosMin">       -52                 -5                   </param>
++>>>>>>> New hardware limits on the elbow
          <param name="rotorPosMin">              0                   0                   </param> 
          <param name="rotorPosMax">              0                   0                   </param>
      </group>
```

4. Conflicts on `iCubGenova09/hardware/motorControl/left_leg-eb8-j3_5-mc.xml`:

```
diff --cc iCubGenova09/hardware/motorControl/left_leg-eb8-j3_5-mc.xml
index 4e78b0558,3f06d1163..000000000
--- a/iCubGenova09/hardware/motorControl/left_leg-eb8-j3_5-mc.xml
+++ b/iCubGenova09/hardware/motorControl/left_leg-eb8-j3_5-mc.xml
@@@ -25,7 -25,7 +25,11 @@@
      </group>
  
      <group name="IMPEDANCE">
++<<<<<<< HEAD
 +        <param name="stiffness">                0.1     30.0                10.0                 </param>
++=======
+         <param name="stiffness">                0.1     30.0                 0.45                 </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
          <param name="damping">                  0.05    0.05                0.05                </param>
      </group>
  
@@@ -116,9 -116,9 +120,15 @@@
          <param name="outputType">          current                      </param>
          <param name="fbkControlUnits">     metric_units                 </param>
          <param name="outputControlUnits">  machine_units                </param>
++<<<<<<< HEAD
 +        <param name="kp">            -0.0    -1000       -1000         </param>
 +        <param name="kd">               0        0            0            </param>
 +        <param name="ki">             -0.0     -500         -1000            </param>
++=======
+         <param name="kp">            -0.0    -1000       -400         </param>
+         <param name="kd">               0        0            0            </param>
+         <param name="ki">             -0.0     -500         -40            </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
          <param name="maxOutput">     2500        2500        2500            </param>
          <param name="maxInt">         200        200         200            </param>
          <param name="ko">               0        0           0            </param>
@@@ -127,7 -127,7 +137,11 @@@
          <param name="kff">              1        1           1            </param>
          <param name="kbemf">         -0.0    -0.0009     -0.0003       </param>
          <param name="filterType">       0        0           0            </param>
++<<<<<<< HEAD
 +        <param name="ktau">          -50.0    -128.81    -227.739         </param>
++=======
+         <param name="ktau">          -50.0    -128.81    -318.2379         </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
      </group>
      <!-- custom PIDs: end -->
```

5. Conflicts on `iCubGenova09/hardware/motorControl/right_leg-eb12-j3_5-mc.xml`:

```
diff --cc iCubGenova09/hardware/motorControl/right_leg-eb12-j3_5-mc.xml
index 55fc195c1,6c9365bc7..000000000
--- a/iCubGenova09/hardware/motorControl/right_leg-eb12-j3_5-mc.xml
+++ b/iCubGenova09/hardware/motorControl/right_leg-eb12-j3_5-mc.xml
@@@ -25,7 -25,7 +25,11 @@@
      </group>
  
      <group name="IMPEDANCE">
++<<<<<<< HEAD
 +        <param name="stiffness">                0.1     30.0               10.0                 </param>
++=======
+         <param name="stiffness">                0.1     30.0                 0.45                 </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
          <param name="damping">                  0.05    0.05               0.05                </param>
      </group>
  
@@@ -116,9 -116,9 +120,15 @@@
          <param name="outputType">          current                      </param>
          <param name="fbkControlUnits">     metric_units                 </param>
          <param name="outputControlUnits">  machine_units                </param>
++<<<<<<< HEAD
 +        <param name="kp">               0          1000       1000      </param>
 +        <param name="kd">               0          0          0      </param>
 +        <param name="ki">               0          500        1000    </param>
++=======
+         <param name="kp">               0          1000        400      </param>
+         <param name="kd">               0          0          0      </param>
+         <param name="ki">               0          500          40    </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
          <param name="maxOutput">     2500       2500       2500        </param>
          <param name="maxInt">         200        200        200       </param>
          <param name="ko">               0          0          0     </param>
@@@ -127,7 -127,7 +137,11 @@@
          <param name="kff">              1          1          1     </param>
          <param name="kbemf">         0.00        0.0009     0.0003    </param>
          <param name="filterType">       0          0          0     </param>
++<<<<<<< HEAD
 +        <param name="ktau">          50.0      128.81     227.739     </param>
++=======
+         <param name="ktau">          50.0      128.81     318.2379     </param>
++>>>>>>> Enable torque via current control. Set motor model parameters for the right and left ankle pitch and roll. Set the torque control gains. Set the impedance control gains.
      </group>
      <!-- custom PIDs: end -->
```

Should we keep the most updated parameters for all the cases? @S-Dafarra

**Comment by S-Dafarra** [comment]
But which modifications is this PR adding apart from the logger application?

**Comment by paolo-viceconte** [comment]
> But which modifications is this PR adding apart from the logger application?

Even if the title of the PR is related to the logger application only, this PR originated as a way to align `devel_iCubGenova09` with a series of modifications that we were using on the robot back in time. While this PR was under review, the same modifications (and further updates) have been merged into `devel_iCubGenova09` by other PRs. 

If we solve all the conflicts in favor of the most updated parameters, the only relevant commit in this PR remains ed21781aa46d9b678e5fad7c6555134265dd9028, which I guess is exactly what we want to keep from this PR at this stage.

**Comment by S-Dafarra** [comment]
Yes, I think we can safely ignore all the other modifications and simply merge https://github.com/ami-iit/robots-configuration/commit/ed21781aa46d9b678e5fad7c6555134265dd9028

**Comment by paolo-viceconte** [comment]
> Yes, I think we can safely ignore all the other modifications and simply merge [ed21781](https://github.com/ami-iit/robots-configuration/commit/ed21781aa46d9b678e5fad7c6555134265dd9028)

PR rebased. We can merge if that's ok.

**Review by S-Dafarra — APPROVED** [review]

**Comment by S-Dafarra** [comment]
Thanks!

**Pull request merged**
