### PR TITLE
[iRonCub-Mk3] Add config files without jetpack FTs

### PR DESCRIPTION
**Pull request by gabrielenava**
cc @HosameldinMohamed 

opened this PR to not loose track of robots configuration branches

### CODE REVIEW

**Comment by HosameldinMohamed** [comment]
Now if we have the jetpack we uncomment the lines

```xml
<xi:include href="wrappers/FT/left_arm_jetpack-FT_remapper.xml" />
<xi:include href="wrappers/FT/right_arm_jetpack-FT_remapper.xml" />
```

And 

```xml
<xi:include href="hardware/FT/left_arm_jetpack-eb1-j0_1-strain.xml" />
<xi:include href="hardware/FT/right_arm_jetpack-eb3-j0_1-strain.xml" />
```


And comment the lines

```xml
<xi:include href="wrappers/FT/left_arm-FT_remapper.xml" />
<xi:include href="wrappers/FT/right_arm-FT_remapper.xml" />
```


And vice versa,,

Not sure it's the cleanest way 😕 

Otherwise we keep 2 robotinterface launch files, but then they will have duplicate lines and we will have to maintain them!

**Comment by gabrielenava** [comment]
>Not sure it's the cleanest way 😕

not sure either, let's say that among the three solutions:

- have two different robotinterface launch files
- have two different branches
- comment/uncomment the lines every time

the first one (have two different robotinterface launch files) is probably the cleanest, with the default version (with FTs on jetpack) pointed in https://github.com/ami-iit/robots-configuration/blob/devel_iRonCub_Mk3_update_jetpack_fts/iRonCub-Mk3/yarprobotinterface.ini, while for the other config file we add the prefix when needed.

**Comment by HosameldinMohamed** [comment]
> > Not sure it's the cleanest way 😕
> 
> not sure either, let's say that among the three solutions:
> 
> * have two different robotinterface launch files
> * have two different branches
> * comment/uncomment the lines every time
> 
> the first one (have two different robotinterface launch files) is probably the cleanest, with the default version (with FTs on jetpack) pointed in https://github.com/ami-iit/robots-configuration/blob/devel_iRonCub_Mk3_update_jetpack_fts/iRonCub-Mk3/yarprobotinterface.ini, while for the other config file we add the prefix when needed.

I prefer the first option!

CC @davidegorbani

**Comment by davidegorbani** [comment]
> I prefer the first option!

I agree with you!

**Comment by HosameldinMohamed** [comment]
Done in https://github.com/ami-iit/robots-configuration/pull/35/commits/4de66a378554aba7314f80104c07c0937153af11

**Comment by HosameldinMohamed** [comment]
Now we have `iRonCub_wbd.xml` that launches the whole robot with the jetpack. And it's the default file pointed out by `yarprobotinterface.ini`.

We have `iRonCub_wbd_no-jetpack.xml` which launches the whole robot without the jetpack FTs.

Tested `iRonCub_wbd_no-jetpack.xml` and robot started with no errors.

**Pull request merged**
