### PR TITLE
Icubgenova09/test kf

### PR DESCRIPTION
**Pull request by isorrentino**
This branch is rebased on https://github.com/ami-iit/robots-configuration/tree/icubgenova09/ft_imus.

Let's wait fot the merging of https://github.com/ami-iit/robots-configuration/tree/icubgenova09/ft_imus and then we can proceed with this PR.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Let's wait for https://github.com/ami-iit/robots-configuration/pull/17 to be merged first

**Comment by S-Dafarra** [comment]
@isorrentino can you rebase this branch?

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by S-Dafarra** [comment]
Do you think this might affect the walking performances?

**Comment by GiulioRomualdi** [comment]
The walking does not use directly the velocity so in theory no. However, I wouldn't bet on it 🥲

**Comment by S-Dafarra** [comment]
I tried and it is walking as usual. Merging

**Pull request merged**
