### PR TITLE
[ergoCubSN000] Add yarpmotorgui custom positions

### PR DESCRIPTION
**Pull request by lrapetti**
Adding file with the custom positions for `ergoCubSN00`.

Feel free to suggest a better name for the file (e.g. `yarpmotorgui_custom_positions`, `home_positions`).
cc @GiulioRomualdi @S-Dafarra @mebbaid @traversaro

### CODE REVIEW

**Review by mebbaid — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
We need to install them via cmake, right?

**Comment by S-Dafarra** [comment]
> We need to install them via cmake, right?

Unless we add the corresponding folder to the ``YARP_DATA_DIRS``. Actually, I would suggest to add it to a folder named ``extra`` that is not installed

**Comment by S-Dafarra** [comment]
> > We need to install them via cmake, right?
> 
> Unless we add the corresponding folder to the `YARP_DATA_DIRS`. Actually, I would suggest to add it to a folder named `extra` that is not installed

Actually, thinking about it again, it is probably better as is. It should be installed as all the other ``.xml`` files, so it should easily found by ``yarp`` resource finder.

**Comment by lrapetti** [comment]
The cmake machinery taking care of installing the `.ini` in that location should be already in place (see https://github.com/ami-iit/robots-configuration/blob/36a85680b378805d53d46e4e795d68706d790aa9/ergoCubSN000/CMakeLists.txt#L7) installing the file in `.../ICUBcontrib/robots/ergoCubSN000` so the file is found if the `YARP_ROBOT_NAME` is properly defined.

**Pull request merged**
